[colors.bright]
black = "0x3e3c3a"
blue = "0x6393d2"
magenta = "0xc8789c"
red = "0xcf7a6b"
yellow = "0xb88846"
green = "0x6d9e46"
cyan = "0x579c96"
white = "0xeeecea"

[colors.normal]
black = "0x1e1c1a"
blue = "0xaad6ff"
magenta = "0xffbbe1"
red = "0xffbdac"
yellow = "0xffcb85"
green = "0xb0e386"
cyan = "0x9be1da"
white = "0xceccca"

[colors.primary]
background = "0x1e1c1a"
foreground = "0xffffff"
